### ISSUE TITLE
Suggestion: screw sizing

### ISSUE THREAD

**Issue by scruss** [milador/Enabled-Controller#1]
Hey, lovely project here!

One (very) minor thing: there's no explicit length on the BOM for the 6-32 screw. I can see from the Digikey part link it's ½", but nothing on the documentation.

Also, could an M3 by 12 mm cross head screw be substituted? I couldn't quite work out if it would be quite long enough. 6-32 screws aren't easily available outside North America, and slot-head screw drivers are classed as bladed tools, so aren't permitted in schools in some countries.

**Comment by milador** [comment]
Good point there. M3 by 6 mm should work but I haven’t got chance to try different options. Had these around so used them. I update the link once I try it. Great feedback as usual. Made the mini version with Adafruit QT PY as well.

**Comment by milador** [comment]
@scruss Changed the screws to M3 and they work well. Thanks for your excellent feedback.
